if [[ $OSTYPE == darwin* ]]; then
    source ~/.zsh/osspecific/darwin.zsh
  else
    source ~/.zsh/osspecific/linux.zsh
fi
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="/usr/local/share/npm/bin/:$PATH"
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
