# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="bitboxer"

# Comment this out to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable command autocorrection
DISABLE_CORRECTION="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(brew bundler dirhelper extract forklift jump rbenv gem zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

export EDITOR=vi

source ~/.zsh/paths.sh
source ~/.zsh/aliases.sh
source ~/.zsh/bitcrowd.sh
source ~/.zsh/git.sh
source ~/.zsh/colorify.sh
source ~/.zsh/fzf.sh
source ~/.zsh/logo.sh

