---
- name: Install the required packages
  hosts: all
  vars:
    user_name: "Bodo Tasche"
    email: "bodo@wannawork.de"
    url: "https://bitboxer.de"
    ruby_version: 2.7.1
    rust_version: 1.46.0
    elixir_version: 1.10.0
    erlang_version: 23.1
    node_version: 14.13.0
    terraform_version: 0.11.7 
    go_version: "1.15"
    neovim_version: 0.4.4
    phantom_version: 2.1.1
    delta_version: 0.12.1
    tmux_version: 3.1b
    java_version: openjdk-11.0.1
    apt_keys:
      - "https://download.docker.com/linux/ubuntu/gpg"
    apt_repositories:
      - "deb [arch=amd64] https://download.docker.com/linux/ubuntu artful stable"
      - "ppa:git-core/ppa"
    apt_packages:
      - autoconf
      - automake
      - bat
      - build-essential
      - chromium-chromedriver
      - cmake
      - curl
      - dirmngr
      - docker-ce
      - exuberant-ctags
      - ffmpeg
      - g++
      - gettext
      - git
      - git-crypt
      - gnupg-agent
      - gnupg2
      - gpg
      - grc
      - htop
      - httpie
      - imagemagick
      - inotify-tools
      - jq
      - libevent-dev
      - libncurses5-dev
      - libtool
      - libtool-bin
      - meld
      - pkg-config
      - postgresql
      - pwgen
      - python3-pip
      - software-properties-common
      - tig
      - tree
      - unzip
      - virtualbox-guest-additions-iso
      - wget
      - xorg
      - xsel
      - youtube-dl
      - zsh
    npm_packages:
      - alex
      - bower
      - gulp
      - jscs
      - jshint
      - jwtgen
      - markdownlint-cli
      - tldr
      - yarn
    ruby_gems:
      - awesome_print
      - bundler
      - github_changelog_generator
      - manpages
      - mdless
      - neovim
      - pry
      - tmuxinator
    cargo_packages:
      - cargo-outdated
      - ripgrep
      - rustfmt
      - exa
      - topgrade
    go_packages:
      - github/hub
      - hetznercloud/cli/cmd/hcloud
      - simeji/jid/cmd/jid
    marks:
      c: /home/vagrant/code
      d: /home/vagrant/Downloads
    spell_files:
      - en.utf-8.spl
      - en.utf-8.sug
      - de.utf-8.spl
      - de.utf-8.sug
  tasks:
    - name: Update permission on persistant storage
      command: chown vagrant:vagrant /home/vagrant/persistant
      become: true
    - name: Add vm to hosts file
      command: bash -c "echo \"127.0.0.1 vm\" >> /etc/hosts"
      become: true
    - name: Symlink code directory
      file: src=/home/vagrant/persistant/code dest=/home/vagrant/code state=link
    - shell: ls -1 /vagrant/tilde
      register: dotfiles
    - name: Link Dotfiles
      file: path=/home/vagrant/.{{ item }} src=/vagrant/tilde/{{ item }} owner=vagrant group=vagrant state=link
      with_items: "{{ dotfiles.stdout_lines }}"
    - name: Add APT Keys
      apt_key: url="{{ item }}"
      with_items: "{{ apt_keys }}"
      become: true
    - name: Add APT Repositories
      apt_repository: repo="{{ item }}" state=present
      with_items: "{{ apt_repositories }}"
      become: true
    - apt: name=aptitude
      become: true
    - name: Update cache and upgrade
      apt: update_cache=yes upgrade=safe
      become: true
    - name: Install missing packages
      apt: name="{{ apt_packages }}"
      become: true

    - name: replace gpg-agent config
      command: bash -c "echo \"default-cache-ttl 21600\\nmax-cache-ttl 259200\" > ~/.gnupg/gpg-agent.conf"

    - name: Install oh-my-zsh
      git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/home/vagrant/.oh-my-zsh
    - name: Install zsh-syntax-highlighting
      git: repo=https://github.com/zsh-users/zsh-syntax-highlighting.git dest=/home/vagrant/.zsh-syntax-highlighting/

    - name: Install antibody
      command: bash -c "curl -sfL git.io/antibody | sh -s - -b /usr/local/bin"
      become: true
      args:
        creates: /usr/local/bin/antibody

    - name: Start docker on boot
      systemd: name=docker enabled=yes
    - name: Make sure the docker group exists
      group:
        name: docker
        state: present
      become: true
    - name: Add the vagrant user to the docker group
      user:
        name: vagrant
        groups: docker
        append: yes
      become: true
    - name: install docker-compose
      command: bash -c "/vagrant/tilde/bin/update_docker_compose"
      become: true

    - name: Set the timezone
      command: timedatectl set-timezone Europe/Berlin
      become: true

    - name: Set default shell for Vagrant user
      user: name=vagrant shell=/bin/zsh
      become: true

    - name: Create the marks directory
      file: path=/home/vagrant/.marks state=directory
    - name: Configure the marks
      file: path=/home/vagrant/.marks/{{ item.key }} state=link src={{ item.value }} force=yes
      with_dict: "{{ marks }}"

    - name: Install asdf
      shell: |
        rm -rf ~/.asdf || true
        git clone https://github.com/asdf-vm/asdf.git ~/.asdf
        cd ~/.asdf
        git checkout "$(git describe --abbrev=0 --tags)"
      args:
        warn: no
    - name: Install asdf plugins
      shell: |
        ~/.asdf/bin/asdf plugin-add erlang http://github.com/asdf-vm/asdf-erlang
        ~/.asdf/bin/asdf plugin-add elixir http://github.com/asdf-vm/asdf-elixir
        ~/.asdf/bin/asdf plugin-add ruby http://github.com/asdf-vm/asdf-ruby
        ~/.asdf/bin/asdf plugin-add nodejs http://github.com/asdf-vm/asdf-nodejs
        ~/.asdf/bin/asdf plugin-add golang http://github.com/kennyp/asdf-golang
        ~/.asdf/bin/asdf plugin-add rust http://github.com/code-lever/asdf-rust
        ~/.asdf/bin/asdf plugin-add terraform https://github.com/Banno/asdf-hashicorp
        ~/.asdf/bin/asdf plugin-add java

    - name: Install erlang
      command: ~/.asdf/bin/asdf install erlang {{ erlang_version }}
      args:
        chdir: ~/
    - name: Install elixir
      command: ~/.asdf/bin/asdf install elixir {{ elixir_version }}
      args:
        chdir: ~/
    - name: Install ruby
      command: ~/.asdf/bin/asdf install ruby {{ ruby_version }}
      args:
        chdir: ~/
    - name: Install node gpg keyring
      command: ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
    - name: Install node
      command: zsh -ic "asdf install nodejs {{ node_version }}"
    - name: Install go
      command: ~/.asdf/bin/asdf install golang {{ go_version }}
      args:
        chdir: ~/
    - name: Install rust
      command: ~/.asdf/bin/asdf install rust {{ rust_version }}
      args:
        chdir: ~/
    - name: Install terraform
      command: ~/.asdf/bin/asdf install terraform {{ terraform_version }}
      args:
        chdir: ~/
    - name: Install java
      command: ~/.asdf/bin/asdf install java {{ java_version }}
      args:
        chdir: ~/
    - name: store versions
      shell: |
        echo erlang {{ erlang_version }} >> ~/.tool-versions
        echo elixir {{ elixir_version }} >> ~/.tool-versions
        echo ruby {{ ruby_version }} >> ~/.tool-versions
        echo nodejs {{ node_version }} >> ~/.tool-versions
        echo golang {{ go_version }} >> ~/.tool-versions
        echo rust {{ rust_version }} >> ~/.tool-versions
        echo terraform {{ terraform_version }} >> ~/.tool-versions
        echo java {{ java_version }} >> ~/.tool-versions

    - name: Reshim all installed packages
      command: ~/.asdf/bin/asdf reshim

    - name: Install default Ruby gems
      command: /bin/zsh -c 'source /home/vagrant/.asdf/asdf.sh && gem install {{ item }}'
      with_items: "{{ ruby_gems }}"

    - name: Install default NPM packages
      command: /bin/zsh -c 'source /home/vagrant/.asdf/asdf.sh && cd ~/ && npm install -g {{ item }}'
      with_items: "{{ npm_packages }}"

    - command: /bin/zsh -c 'source /home/vagrant/.asdf/asdf.sh && cd ~/ && npm set init-author-name "{{ user_name }}"'
    - command: /bin/zsh -c 'source /home/vagrant/.asdf/asdf.sh && cd ~/ && npm set init-author-email"{{ email }}"'
    - command: /bin/zsh -c 'source /home/vagrant/.asdf/asdf.sh && cd ~/ && npm set init-author-url "{{ url }}"'

    - name: Install Cargo packages
      command: /bin/zsh -c 'source /home/vagrant/.asdf/asdf.sh && cargo install --verbose --force {{ item }}'
      with_items: "{{ cargo_packages }}"

    - name: Install go packages
      command: /bin/zsh -c 'source /home/vagrant/.asdf/asdf.sh && go get -u github.com/{{ item }}'
      with_items: "{{ go_packages }}"

    - name: Reshim all installed packages
      command: ~/.asdf/bin/asdf reshim

    - name: Download phantomjs
      get_url: url=https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-{{ phantom_version }}-linux-x86_64.tar.bz2 dest=/tmp/phantomjs.tar.bz2
      become: true
    - name: Unarchive phantomjs
      unarchive: src=/tmp/phantomjs.tar.bz2 dest=/tmp copy=false
      become: true
    - name: Move phantomjs
      command: cp /tmp/phantomjs-{{ phantom_version }}-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs
      become: true

    - name: Download NeoVim
      get_url: >
        url=https://github.com/neovim/neovim/archive/v{{ neovim_version }}.tar.gz
        dest=/tmp/neovim-{{ neovim_version }}.tar.gz
    - name: Uncompress NeoVim archive
      unarchive: >
        src=/tmp/neovim-{{ neovim_version }}.tar.gz
        dest=/tmp   
        copy=no
    - name: Install NeoVim
      command: bash -c "CMAKE_BUILD_TYPE=RelWithDebInfo make && sudo make install"
      args:
        chdir: /tmp/neovim-{{ neovim_version }}
    - name: Install vimplug
      git: repo=https://github.com/junegunn/vim-plug.git dest=/home/vagrant/.vimplug
    - name: Linking vimplug
      command: bash -c "mkdir -p ~/.config/nvim/autoload/ && cp -f $HOME/.vimplug/plug.vim $HOME/.config/nvim/autoload/plug.vim"
    - name: Install neovim python3 binding
      command: pip3 install neovim
      become: true
    - name: Install neovim packages
      command: nvim +PlugInstall +UpdateRemotePlugin +qa

    - name: Download fzf
      git: repo=https://github.com/junegunn/fzf.git dest=/home/vagrant/.fzf
    - name: Install fzf
      command: /bin/zsh -c 'source /home/vagrant/.asdf/asdf.sh && /home/vagrant/.fzf/install --all --no-update-rc --no-bash --no-fish'

    - name: Download tmux
      get_url: >
        url=https://github.com/tmux/tmux/releases/download/{{ tmux_version }}/tmux-{{ tmux_version }}.tar.gz
        dest=/tmp/tmux.tar.gz
      become: true
    - name: Unarchive tmux
      unarchive: src=/tmp/tmux.tar.gz dest=/tmp copy=false
      become: true
    - name: Install tmux
      command: bash -c "cd /tmp/tmux-{{ tmux_version }} && ./configure && make && make install"
      become: true

    - name: Download delta
      get_url: >
        url=https://github.com/dandavison/delta/releases/download/{{ delta_version }}/git-delta_{{ delta_version }}_amd64.deb
        dest=/tmp/delta_amd64.deb
      become: true
    - name: Install delta
      command: dpkg -i /tmp/delta_arm64.deb
      become: true

    - name: Download tmux-yank
      git: repo=https://github.com/tmux-plugins/tmux-yank.git dest=/home/vagrant/.tmux-yank

    - name: install awscli
      command: pip install awscli --user

    - name: Mark the box as vagrant box to check in shell scripts
      become: true
      file: path=/etc/is_vagrant_vm state=touch owner=root group=sys mode=0777

    - name: Increase file watcher limits
      become: true
      command: bash -c "echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p && sysctl --system"
    
    - name: Install github client
      become: true
      command: bash -c "apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0; apt-add-repository https://cli.github.com/packages; apt update; apt install gh"
