# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  - trigger: ":vat"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "cat $HOME/.secrets.vat"
          debug: true
  - trigger: ":reg"
    replace: "Best regards,\nBodo Tasche"
  - trigger: ":mfg"
    replace: "Mit freundlichen Grüßen,\nBodo Tasche"
  - trigger: ":mdl"
    replace: "[$|$]({{clipboard}})"
    vars:
      - name: "clipboard"
        type: "clipboard"
  - trigger: ":clog"
    replace: "console.log($|$)"

  - trigger: ":extip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl ifconfig.me"
  - trigger: ":ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "ifconfig -l | xargs -n1 ipconfig getifaddr"

  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":flip"
    replace: "(╯°□°）╯︵ ┻━┻"

  - trigger: ":sloth"
    replace: "🦥"
