# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  - trigger: ":vat:"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "cat $HOME/.secrets.vat"
          debug: true
  - trigger: ":reg:"
    replace: "Best regards,\nBodo Tasche"
  - trigger: ":mfg:"
    replace: "Mit freundlichen Grüßen,\nBodo Tasche"
  - trigger: ":mdl:"
    replace: "[$|$]({{clipboard}})"
    vars:
      - name: "clipboard"
        type: "clipboard"
  - trigger: ":clog:"
    replace: "console.log($|$)"

  - trigger: ":extip:"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl ifconfig.me"
  - trigger: ":ip:"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "ifconfig -l | xargs -n1 ipconfig getifaddr"

  - trigger: ":date:"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":depreb:"
    replace: "@dependabot rebase"

  - trigger: ":ipsum:"
    replace: "Chase ball of string eat plants, meow, and throw up because I ate plants going to catch the red dot today going to catch the red dot today. I could pee on this if I had the energy. Chew iPad power cord steal the warm chair right after you get up for purr for no reason leave hair everywhere, decide to want nothing to do with my owner today."
      
